using System;
using Microsoft.EntityFrameworkCore.Migrations;

// <auto-generated />
#nullable disable

namespace ToDoApp.Migrations.Application;
    /// <inheritdoc />
    public partial class add_entities : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "to_do_app");

            migrationBuilder.CreateTable(
                name: "todo_tasks",
                schema: "to_do_app",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    title = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    is_completed = table.Column<bool>(type: "boolean", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    last_completed_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_todo_tasks", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "users",
                schema: "to_do_app",
                columns: table => new
                {
                    id = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    user_name = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    email = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    updated_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_users", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "user_todo_tasks",
                schema: "to_do_app",
                columns: table => new
                {
                    user_id = table.Column<string>(type: "character varying(500)", nullable: false),
                    todo_task_id = table.Column<string>(type: "character varying(500)", nullable: false),
                    created_at_utc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_user_todo_tasks", x => new { x.user_id, x.todo_task_id });
                    table.ForeignKey(
                        name: "fk_user_todo_tasks_todo_tasks_todo_task_id",
                        column: x => x.todo_task_id,
                        principalSchema: "to_do_app",
                        principalTable: "todo_tasks",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_user_todo_tasks_users_user_id",
                        column: x => x.user_id,
                        principalSchema: "to_do_app",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "ix_user_todo_tasks_todo_task_id",
                schema: "to_do_app",
                table: "user_todo_tasks",
                column: "todo_task_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "user_todo_tasks",
                schema: "to_do_app");

            migrationBuilder.DropTable(
                name: "todo_tasks",
                schema: "to_do_app");

            migrationBuilder.DropTable(
                name: "users",
                schema: "to_do_app");
        }
    }

